/*
 * Copyright 1998 Visual Systems Corporation
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Neither the name "Visual Systems" nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY VISUAL SYSTEMS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL VISUAL SYSTEMS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

package com.vscorp.ui.swing.redirector;

import java.lang.reflect.Method;

/** Redirector for java.awt.event.KeyListener.
 * Automatically generated by GenRedirectors. Do not modify directly.
 */

public class KeyRedirector extends EventRedirector implements java.awt.event.KeyListener {
	private Method keyPressedMethod;
	private Method keyReleasedMethod;
	private Method keyTypedMethod;

	public KeyRedirector(Object anEventReceiver, 
			String keyPressedMethodName, 
			String keyReleasedMethodName, 
			String keyTypedMethodName) {
		super(anEventReceiver);
		keyPressedMethod = getEventMethod(keyPressedMethodName, java.awt.event.KeyEvent.class);
		keyReleasedMethod = getEventMethod(keyReleasedMethodName, java.awt.event.KeyEvent.class);
		keyTypedMethod = getEventMethod(keyTypedMethodName, java.awt.event.KeyEvent.class);
	}

	// Interface Methods:
	public void keyPressed(java.awt.event.KeyEvent anEvent) {
		callEventMethod(keyPressedMethod, anEvent);
	}
	public void keyReleased(java.awt.event.KeyEvent anEvent) {
		callEventMethod(keyReleasedMethod, anEvent);
	}
	public void keyTyped(java.awt.event.KeyEvent anEvent) {
		callEventMethod(keyTypedMethod, anEvent);
	}
}
