/*
 * Copyright 1998 Visual Systems Corporation
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Neither the name "Visual Systems" nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY VISUAL SYSTEMS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL VISUAL SYSTEMS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

package com.vscorp.ui.swing.redirector;

import java.lang.reflect.Method;

/** Redirector for javax.swing.event.MenuListener.
 * Automatically generated by GenRedirectors. Do not modify directly.
 */

public class MenuRedirector extends EventRedirector implements javax.swing.event.MenuListener {
	private Method menuCanceledMethod;
	private Method menuDeselectedMethod;
	private Method menuSelectedMethod;

	public MenuRedirector(Object anEventReceiver, 
			String menuCanceledMethodName, 
			String menuDeselectedMethodName, 
			String menuSelectedMethodName) {
		super(anEventReceiver);
		menuCanceledMethod = getEventMethod(menuCanceledMethodName, javax.swing.event.MenuEvent.class);
		menuDeselectedMethod = getEventMethod(menuDeselectedMethodName, javax.swing.event.MenuEvent.class);
		menuSelectedMethod = getEventMethod(menuSelectedMethodName, javax.swing.event.MenuEvent.class);
	}

	// Interface Methods:
	public void menuCanceled(javax.swing.event.MenuEvent anEvent) {
		callEventMethod(menuCanceledMethod, anEvent);
	}
	public void menuDeselected(javax.swing.event.MenuEvent anEvent) {
		callEventMethod(menuDeselectedMethod, anEvent);
	}
	public void menuSelected(javax.swing.event.MenuEvent anEvent) {
		callEventMethod(menuSelectedMethod, anEvent);
	}
}
