/*
 * Copyright 1998 Visual Systems Corporation
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Neither the name "Visual Systems" nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY VISUAL SYSTEMS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL VISUAL SYSTEMS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

package com.vscorp.ui.swing.redirector;

import java.lang.reflect.Method;

/** Redirector for java.awt.event.WindowListener.
 * Automatically generated by GenRedirectors. Do not modify directly.
 */

public class WindowRedirector extends EventRedirector implements java.awt.event.WindowListener {
	private Method windowActivatedMethod;
	private Method windowClosedMethod;
	private Method windowClosingMethod;
	private Method windowDeactivatedMethod;
	private Method windowDeiconifiedMethod;
	private Method windowIconifiedMethod;
	private Method windowOpenedMethod;

	public WindowRedirector(Object anEventReceiver, 
			String windowActivatedMethodName, 
			String windowClosedMethodName, 
			String windowClosingMethodName, 
			String windowDeactivatedMethodName, 
			String windowDeiconifiedMethodName, 
			String windowIconifiedMethodName, 
			String windowOpenedMethodName) {
		super(anEventReceiver);
		windowActivatedMethod = getEventMethod(windowActivatedMethodName, java.awt.event.WindowEvent.class);
		windowClosedMethod = getEventMethod(windowClosedMethodName, java.awt.event.WindowEvent.class);
		windowClosingMethod = getEventMethod(windowClosingMethodName, java.awt.event.WindowEvent.class);
		windowDeactivatedMethod = getEventMethod(windowDeactivatedMethodName, java.awt.event.WindowEvent.class);
		windowDeiconifiedMethod = getEventMethod(windowDeiconifiedMethodName, java.awt.event.WindowEvent.class);
		windowIconifiedMethod = getEventMethod(windowIconifiedMethodName, java.awt.event.WindowEvent.class);
		windowOpenedMethod = getEventMethod(windowOpenedMethodName, java.awt.event.WindowEvent.class);
	}

	// Interface Methods:
	public void windowActivated(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowActivatedMethod, anEvent);
	}
	public void windowClosed(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowClosedMethod, anEvent);
	}
	public void windowClosing(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowClosingMethod, anEvent);
	}
	public void windowDeactivated(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowDeactivatedMethod, anEvent);
	}
	public void windowDeiconified(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowDeiconifiedMethod, anEvent);
	}
	public void windowIconified(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowIconifiedMethod, anEvent);
	}
	public void windowOpened(java.awt.event.WindowEvent anEvent) {
		callEventMethod(windowOpenedMethod, anEvent);
	}
}
