//Ener-J
//Copyright 2000-2006 Visual Systems Corporation
//$Header: /cvsroot/ener-j/ener-j/src/org/enerj/annotations/SchemaAnnotation.java,v 1.1 2006/05/02 22:05:24 dsyrstad Exp $

package org.enerj.annotations;

import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Annotation for a schema generated by the enhancer. <p>
 * 
 * @version $Id: SchemaAnnotation.java,v 1.1 2006/05/02 22:05:24 dsyrstad Exp $
 * @author <a href="mailto:dsyrstad@ener-j.org">Dan Syrstad </a>
 */
@Target(TYPE) @Retention(RUNTIME)
public @interface SchemaAnnotation {
    /** Original, unenhanced bytecodes for this class. */
    byte[] originalByteCodes();
    
    /** Class ID hash of this class. */
    long classID();
    
    /** Persistent field names */
    String[] persistentFieldNames();
    
    /** Transient field names. Needed to enhance PersistenceAware classes. */
    String[] transientFieldNames();
    
}
