/*
 * Copyright 1998 Visual Systems Corporation
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Neither the name "Visual Systems" nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY VISUAL SYSTEMS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL VISUAL SYSTEMS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

package com.vscorp.ui.swing.redirector;

import java.lang.reflect.Method;

/** Redirector for javax.swing.event.InternalFrameListener.
 * Automatically generated by GenRedirectors. Do not modify directly.
 */

public class InternalFrameRedirector extends EventRedirector implements javax.swing.event.InternalFrameListener {
	private Method internalFrameActivatedMethod;
	private Method internalFrameClosedMethod;
	private Method internalFrameClosingMethod;
	private Method internalFrameDeactivatedMethod;
	private Method internalFrameDeiconifiedMethod;
	private Method internalFrameIconifiedMethod;
	private Method internalFrameOpenedMethod;

	public InternalFrameRedirector(Object anEventReceiver, 
			String internalFrameActivatedMethodName, 
			String internalFrameClosedMethodName, 
			String internalFrameClosingMethodName, 
			String internalFrameDeactivatedMethodName, 
			String internalFrameDeiconifiedMethodName, 
			String internalFrameIconifiedMethodName, 
			String internalFrameOpenedMethodName) {
		super(anEventReceiver);
		internalFrameActivatedMethod = getEventMethod(internalFrameActivatedMethodName, javax.swing.event.InternalFrameEvent.class);
		internalFrameClosedMethod = getEventMethod(internalFrameClosedMethodName, javax.swing.event.InternalFrameEvent.class);
		internalFrameClosingMethod = getEventMethod(internalFrameClosingMethodName, javax.swing.event.InternalFrameEvent.class);
		internalFrameDeactivatedMethod = getEventMethod(internalFrameDeactivatedMethodName, javax.swing.event.InternalFrameEvent.class);
		internalFrameDeiconifiedMethod = getEventMethod(internalFrameDeiconifiedMethodName, javax.swing.event.InternalFrameEvent.class);
		internalFrameIconifiedMethod = getEventMethod(internalFrameIconifiedMethodName, javax.swing.event.InternalFrameEvent.class);
		internalFrameOpenedMethod = getEventMethod(internalFrameOpenedMethodName, javax.swing.event.InternalFrameEvent.class);
	}

	// Interface Methods:
	public void internalFrameActivated(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameActivatedMethod, anEvent);
	}
	public void internalFrameClosed(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameClosedMethod, anEvent);
	}
	public void internalFrameClosing(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameClosingMethod, anEvent);
	}
	public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameDeactivatedMethod, anEvent);
	}
	public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameDeiconifiedMethod, anEvent);
	}
	public void internalFrameIconified(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameIconifiedMethod, anEvent);
	}
	public void internalFrameOpened(javax.swing.event.InternalFrameEvent anEvent) {
		callEventMethod(internalFrameOpenedMethod, anEvent);
	}
}
