/*
 * Copyright 1998 Visual Systems Corporation
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Neither the name "Visual Systems" nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY VISUAL SYSTEMS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL VISUAL SYSTEMS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

package com.vscorp.ui.swing.redirector;

import java.lang.reflect.Method;

/** Redirector for javax.swing.event.MenuKeyListener.
 * Automatically generated by GenRedirectors. Do not modify directly.
 */

public class MenuKeyRedirector extends EventRedirector implements javax.swing.event.MenuKeyListener {
	private Method menuKeyPressedMethod;
	private Method menuKeyReleasedMethod;
	private Method menuKeyTypedMethod;

	public MenuKeyRedirector(Object anEventReceiver, 
			String menuKeyPressedMethodName, 
			String menuKeyReleasedMethodName, 
			String menuKeyTypedMethodName) {
		super(anEventReceiver);
		menuKeyPressedMethod = getEventMethod(menuKeyPressedMethodName, javax.swing.event.MenuKeyEvent.class);
		menuKeyReleasedMethod = getEventMethod(menuKeyReleasedMethodName, javax.swing.event.MenuKeyEvent.class);
		menuKeyTypedMethod = getEventMethod(menuKeyTypedMethodName, javax.swing.event.MenuKeyEvent.class);
	}

	// Interface Methods:
	public void menuKeyPressed(javax.swing.event.MenuKeyEvent anEvent) {
		callEventMethod(menuKeyPressedMethod, anEvent);
	}
	public void menuKeyReleased(javax.swing.event.MenuKeyEvent anEvent) {
		callEventMethod(menuKeyReleasedMethod, anEvent);
	}
	public void menuKeyTyped(javax.swing.event.MenuKeyEvent anEvent) {
		callEventMethod(menuKeyTypedMethod, anEvent);
	}
}
